### Sort, Search & Counting Functions.

In [1]:
import numpy as  np

In [2]:
arr = np.array([4,3,5,6,72,3,3,455,5,6,6])

In [3]:
arr

array([  4,   3,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [5]:
np.sort(arr)

array([  3,   3,   3,   4,   5,   5,   6,   6,   6,  72, 455])

In [6]:
np.searchsorted(arr,34) #This will telld us at which index 34 will be placed so, answer is at 11th index

11

In [7]:
arr1 = np.array([0,345,453,0,0,0,0,0,0])

In [10]:
np.count_nonzero(arr1) #This will return number of nonzero elements

2

In [11]:
arr

array([  4,   3,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [12]:
np.where(arr > 6) #This will tels us at which index value which are > than 6 is present
#So, answer is 4 and 7

(array([4, 7], dtype=int64),)

In [13]:
np.extract(arr>6, arr) #This will extract the elements which are > 6

array([ 72, 455])

### Numpy - Byte Swapping.

In [14]:
arr 

array([  4,   3,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [16]:
arr.byteswap() #This will show all byte representation of the data which are present

array([  67108864,   50331648,   83886080,  100663296, 1207959552,
         50331648,   50331648, -956235776,   83886080,  100663296,
        100663296])

### Numpy - Copies & Views.

In [17]:
arr

array([  4,   3,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [19]:
a = np.copy(arr) #Deep copy

In [25]:
b = arr.view() #shallow copy

In [26]:
b = arr #shallow copy

In [27]:
b

array([ 67,   3,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [22]:
arr

array([  4,   3,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [23]:
b[0] = 67


In [24]:
arr

array([ 67,   3,   5,   6,  72,   3,   3, 455,   5,   6,   6])

### Numpy - Matrix Library.

In [28]:
import numpy.matlib as nm

In [29]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [30]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [39]:
arr1 = nm.random.randint(1,5,(2,3))

In [40]:
arr2 = nm.random.randint(1,5,(2,3))

In [43]:
arr1

array([[4, 3, 2],
       [3, 4, 1]])

In [44]:
arr2

array([[1, 2, 2],
       [4, 2, 1]])

In [45]:
arr1+arr2

array([[5, 5, 4],
       [7, 6, 2]])

In [46]:
arr1-arr2

array([[ 3,  1,  0],
       [-1,  2,  0]])

In [48]:
arr1*arr2

array([[ 4,  6,  4],
       [12,  8,  1]])

### Numpy - Linear Algebra

In [51]:
arr1 = np.random.randint([[2,3], [4,5]])

In [52]:
arr2 = np.random.randint([[2,3], [4,5]])

In [53]:
arr1

array([[0, 0],
       [2, 1]])

In [54]:
arr2

array([[0, 2],
       [0, 2]])

In [55]:
np.dot(arr1,arr2)

array([[0, 0],
       [0, 6]])

In [56]:
arr1@arr2

array([[0, 0],
       [0, 6]])