### Numpy - Array Manipulation.

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,(3,4))

In [3]:
arr

array([[7, 2, 6, 8],
       [3, 7, 8, 2],
       [3, 5, 6, 6]])

In [7]:
arr.reshape(6,2)

array([[7, 2],
       [6, 8],
       [3, 7],
       [8, 2],
       [3, 5],
       [6, 6]])

In [8]:
arr.reshape(2,6)

array([[7, 2, 6, 8, 3, 7],
       [8, 2, 3, 5, 6, 6]])

In [9]:
arr.reshape(2,7)

ValueError: cannot reshape array of size 12 into shape (2,7)

In [10]:
arr.reshape(2,-242342)

array([[7, 2, 6, 8, 3, 7],
       [8, 2, 3, 5, 6, 6]])

In [11]:
arr.T

array([[7, 3, 3],
       [2, 7, 5],
       [6, 8, 6],
       [8, 2, 6]])

In [14]:
arr.transpose

<function ndarray.transpose>

In [15]:
arr.transpose()

array([[7, 3, 3],
       [2, 7, 5],
       [6, 8, 6],
       [8, 2, 6]])

In [16]:
arr

array([[7, 2, 6, 8],
       [3, 7, 8, 2],
       [3, 5, 6, 6]])

In [18]:
arr.flatten() #This will convert entire data in 1-D

array([7, 2, 6, 8, 3, 7, 8, 2, 3, 5, 6, 6])

In [19]:
arr1 = np.array([1,2,3,4])

In [21]:
arr1.ndim

1

In [23]:
np.expand_dims(arr1, axis = 1) #This will change the dimension 

array([[1],
       [2],
       [3],
       [4]])

In [24]:
np.expand_dims(arr1,axis = 0)

array([[1, 2, 3, 4]])

In [25]:
arr

array([[7, 2, 6, 8],
       [3, 7, 8, 2],
       [3, 5, 6, 6]])

In [26]:
np.squeeze(arr)

array([[7, 2, 6, 8],
       [3, 7, 8, 2],
       [3, 5, 6, 6]])

In [28]:
data = np.array([[1],[2],[3]])

In [29]:
data

array([[1],
       [2],
       [3]])

In [30]:
np.squeeze(data)

array([1, 2, 3])

In [31]:
arr1 

array([1, 2, 3, 4])

In [33]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [39]:
np.roll(arr1, 2) #This function is used to make shift by 2

array([3, 4, 1, 2])

In [36]:
arr1

array([1, 2, 3, 4])

In [41]:
np.roll(arr1, 3) #This function is use to make shift by 3

array([2, 3, 4, 1])

In [38]:
arr1

array([1, 2, 3, 4])

In [43]:
np.diag(arr1) #This will make a 2-D array and put all 1-D array diagonally 

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### Numpy - Binary Operations.

In [44]:
arr1 = np.random.randint(1,10, (3,4))

In [47]:
arr2 = np.random.randint(1,10, (3,4))

In [48]:
arr1

array([[6, 8, 2, 5],
       [5, 4, 7, 8],
       [4, 1, 8, 8]])

In [49]:
arr2

array([[2, 8, 3, 9],
       [6, 7, 7, 4],
       [4, 4, 2, 6]])

In [50]:
arr1+arr2

array([[ 8, 16,  5, 14],
       [11, 11, 14, 12],
       [ 8,  5, 10, 14]])

In [51]:
arr1*arr2

array([[12, 64,  6, 45],
       [30, 28, 49, 32],
       [16,  4, 16, 48]])

In [52]:
arr1/arr2

array([[3.        , 1.        , 0.66666667, 0.55555556],
       [0.83333333, 0.57142857, 1.        , 2.        ],
       [1.        , 0.25      , 4.        , 1.33333333]])

In [53]:
arr1-arr2

array([[ 4,  0, -1, -4],
       [-1, -3,  0,  4],
       [ 0, -3,  6,  2]])

In [55]:
arr1%arr2

array([[0, 0, 2, 5],
       [5, 4, 0, 0],
       [0, 1, 0, 2]], dtype=int32)

In [56]:
arr1**arr2

array([[      36, 16777216,        8,  1953125],
       [   15625,    16384,   823543,     4096],
       [     256,        1,       64,   262144]], dtype=int32)

In [57]:
arr1 & arr2 #AND Operation

array([[2, 8, 2, 1],
       [4, 4, 7, 0],
       [4, 0, 0, 0]], dtype=int32)

In [58]:
~arr1 

array([[-7, -9, -3, -6],
       [-6, -5, -8, -9],
       [-5, -2, -9, -9]], dtype=int32)

In [59]:
arr1|arr2 #OR Operation

array([[ 6,  8,  3, 13],
       [ 7,  7,  7, 12],
       [ 4,  5, 10, 14]], dtype=int32)

In [61]:
arr1 > arr2

array([[ True, False, False, False],
       [False, False, False,  True],
       [False, False,  True,  True]])

In [62]:
arr1 < arr2

array([[False, False,  True,  True],
       [ True,  True, False, False],
       [False,  True, False, False]])

### Numpy - String Functions.

In [63]:
arr = np.array(['Sudhanshu','Kumar'])

In [65]:
arr

array(['Sudhanshu', 'Kumar'], dtype='<U9')

In [66]:
np.char.upper(arr)

array(['SUDHANSHU', 'KUMAR'], dtype='<U9')

In [67]:
np.char.title(arr)

array(['Sudhanshu', 'Kumar'], dtype='<U9')

In [69]:
np.char.capitalize(arr)

array(['Sudhanshu', 'Kumar'], dtype='<U9')

### Numpy - Mathematical Functions.

In [70]:
arr1

array([[6, 8, 2, 5],
       [5, 4, 7, 8],
       [4, 1, 8, 8]])

In [71]:
np.sin(arr1)

array([[-0.2794155 ,  0.98935825,  0.90929743, -0.95892427],
       [-0.95892427, -0.7568025 ,  0.6569866 ,  0.98935825],
       [-0.7568025 ,  0.84147098,  0.98935825,  0.98935825]])

In [72]:
np.cos(arr1)

array([[ 0.96017029, -0.14550003, -0.41614684,  0.28366219],
       [ 0.28366219, -0.65364362,  0.75390225, -0.14550003],
       [-0.65364362,  0.54030231, -0.14550003, -0.14550003]])

In [73]:
np.tan(arr1)

array([[-0.29100619, -6.79971146, -2.18503986, -3.38051501],
       [-3.38051501,  1.15782128,  0.87144798, -6.79971146],
       [ 1.15782128,  1.55740772, -6.79971146, -6.79971146]])

In [74]:
np.tanh(arr1)

array([[0.99998771, 0.99999977, 0.96402758, 0.9999092 ],
       [0.9999092 , 0.9993293 , 0.99999834, 0.99999977],
       [0.9993293 , 0.76159416, 0.99999977, 0.99999977]])

In [76]:
np.log10(arr1)

array([[0.77815125, 0.90308999, 0.30103   , 0.69897   ],
       [0.69897   , 0.60205999, 0.84509804, 0.90308999],
       [0.60205999, 0.        , 0.90308999, 0.90308999]])

In [77]:
np.exp(arr1)

array([[4.03428793e+02, 2.98095799e+03, 7.38905610e+00, 1.48413159e+02],
       [1.48413159e+02, 5.45981500e+01, 1.09663316e+03, 2.98095799e+03],
       [5.45981500e+01, 2.71828183e+00, 2.98095799e+03, 2.98095799e+03]])

In [78]:
np.sqrt(arr1)

array([[2.44948974, 2.82842712, 1.41421356, 2.23606798],
       [2.23606798, 2.        , 2.64575131, 2.82842712],
       [2.        , 1.        , 2.82842712, 2.82842712]])

In [80]:
np.power(arr1,2)

array([[36, 64,  4, 25],
       [25, 16, 49, 64],
       [16,  1, 64, 64]], dtype=int32)

In [81]:
np.mean(arr1)

5.5

In [85]:
np.median(arr1)

5.5

In [88]:
np.std(arr1)

2.327373340628157

In [95]:
np.var(arr1)

5.416666666666667

In [96]:
np.min(arr1)

1

In [97]:
np.max(arr1)

8

In [98]:
np.sum(arr1)

66